<?php

if (!function_exists('isAbsoluteUrl')) {
    function isAbsoluteUrl(?string $value): bool
    {
        if ($value === null) {
            return false;
        }

        return (bool) preg_match('#^(https?:)?//#i', $value);
    }
}

if (!function_exists('appUsesDatabaseUploads')) {
    function appUsesDatabaseUploads(): bool
    {
        return defined('UPLOAD_DRIVER') && UPLOAD_DRIVER === 'database';
    }
}

if (!function_exists('appUsesSupabaseUploads')) {
    function appUsesSupabaseUploads(): bool
    {
        return defined('UPLOAD_DRIVER') && UPLOAD_DRIVER === 'supabase';
    }
}

if (!function_exists('appUsesLocalUploads')) {
    function appUsesLocalUploads(): bool
    {
        return !appUsesDatabaseUploads() && !appUsesSupabaseUploads();
    }
}

if (!function_exists('appUploadMaxBytes')) {
    function appUploadMaxBytes(): int
    {
        return defined('UPLOAD_MAX_BYTES') ? (int) UPLOAD_MAX_BYTES : 4194304;
    }
}

if (!function_exists('appUploadMaxLabel')) {
    function appUploadMaxLabel(): string
    {
        return number_format(appUploadMaxBytes() / 1048576, 0) . 'MB';
    }
}

if (!function_exists('ensureUploadedFilesTable')) {
    function ensureUploadedFilesTable(PDO $pdo): void
    {
        static $initialized = false;

        if ($initialized) {
            return;
        }

        if (dbIsPgsql($pdo)) {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS uploaded_files (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    storage_key VARCHAR(80) NOT NULL UNIQUE,
                    folder_name VARCHAR(120) NULL,
                    original_name VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(120) NOT NULL,
                    file_size INTEGER NOT NULL DEFAULT 0,
                    content_blob BYTEA NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ");
        } else {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS uploaded_files (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    storage_key VARCHAR(80) NOT NULL UNIQUE,
                    folder_name VARCHAR(120) NULL,
                    original_name VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(120) NOT NULL,
                    file_size INT NOT NULL DEFAULT 0,
                    content_blob LONGBLOB NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ");
        }

        $initialized = true;
    }
}

if (!function_exists('storedFilePathToUrl')) {
    function storedFilePathToUrl(?string $path, ?string $fallback = null): string
    {
        if ($path === null || $path === '') {
            return $fallback ?? '';
        }

        if (strpos($path, 'filedb:') === 0) {
            $storageKey = substr($path, 7);
            return rtrim(BASE_URL, '/') . '/api/file.php?key=' . rawurlencode($storageKey);
        }

        if (strpos($path, 'supabase:') === 0) {
            $storagePath = substr($path, 9);
            $signedUrl = supabaseStorageCreateSignedUrl($storagePath);
            return $signedUrl !== '' ? $signedUrl : ($fallback ?? '');
        }

        if (isAbsoluteUrl($path)) {
            return $path;
        }

        if (strpos($path, 'uploads/') === 0) {
            return rtrim(BASE_URL, '/') . '/public/' . ltrim($path, '/');
        }

        return rtrim(BASE_URL, '/') . '/' . ltrim($path, '/');
    }
}

if (!function_exists('supabaseStorageConfigured')) {
    function supabaseStorageConfigured(): bool
    {
        return defined('SUPABASE_PROJECT_URL')
            && trim((string) SUPABASE_PROJECT_URL) !== ''
            && defined('SUPABASE_SERVICE_ROLE_KEY')
            && trim((string) SUPABASE_SERVICE_ROLE_KEY) !== ''
            && defined('SUPABASE_STORAGE_BUCKET')
            && trim((string) SUPABASE_STORAGE_BUCKET) !== '';
    }
}

if (!function_exists('supabaseStorageBaseUrl')) {
    function supabaseStorageBaseUrl(): string
    {
        return rtrim((string) SUPABASE_PROJECT_URL, '/') . '/storage/v1';
    }
}

if (!function_exists('supabaseStorageRequest')) {
    function supabaseStorageRequest(string $method, string $endpoint, ?string $body = null, array $headers = []): array
    {
        if (!supabaseStorageConfigured()) {
            return ['success' => false, 'status' => 0, 'body' => '', 'error' => 'Supabase Storage is not configured.'];
        }

        $url = supabaseStorageBaseUrl() . '/' . ltrim($endpoint, '/');
        $defaultHeaders = [
            'apikey: ' . SUPABASE_SERVICE_ROLE_KEY,
            'Authorization: Bearer ' . SUPABASE_SERVICE_ROLE_KEY,
        ];

        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_CUSTOMREQUEST => strtoupper($method),
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HEADER => false,
            CURLOPT_FOLLOWLOCATION => false,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTPHEADER => array_merge($defaultHeaders, $headers),
        ]);

        if ($body !== null) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
        }

        $responseBody = curl_exec($ch);
        $error = curl_error($ch);
        $status = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
        curl_close($ch);

        return [
            'success' => $error === '' && $status >= 200 && $status < 300,
            'status' => $status,
            'body' => is_string($responseBody) ? $responseBody : '',
            'error' => $error,
        ];
    }
}

if (!function_exists('supabaseStorageNormalizePath')) {
    function supabaseStorageNormalizePath(string $path): string
    {
        return trim(preg_replace('#/+#', '/', str_replace('\\', '/', $path)), '/');
    }
}

if (!function_exists('supabaseStorageCreateSignedUrl')) {
    function supabaseStorageCreateSignedUrl(string $storagePath, int $expiresIn = 3600): string
    {
        $storagePath = supabaseStorageNormalizePath($storagePath);
        if ($storagePath === '') {
            return '';
        }

        $endpoint = 'object/sign/' . rawurlencode((string) SUPABASE_STORAGE_BUCKET) . '/' . str_replace('%2F', '/', rawurlencode($storagePath));
        $result = supabaseStorageRequest(
            'POST',
            $endpoint,
            json_encode(['expiresIn' => $expiresIn]),
            ['Content-Type: application/json']
        );

        if (!$result['success']) {
            error_log('Supabase signed URL error: ' . json_encode($result));
            return '';
        }

        $data = json_decode($result['body'], true);
        $signedPath = is_array($data) ? ($data['signedURL'] ?? $data['signedUrl'] ?? '') : '';
        if (!is_string($signedPath) || $signedPath === '') {
            return '';
        }

        if (isAbsoluteUrl($signedPath)) {
            return $signedPath;
        }

        return supabaseStorageBaseUrl() . '/' . ltrim($signedPath, '/');
    }
}

if (!function_exists('supabaseStorageObjectExists')) {
    function supabaseStorageObjectExists(string $storagePath, int $attempts = 4, int $delayMicroseconds = 250000): bool
    {
        $storagePath = supabaseStorageNormalizePath($storagePath);
        if ($storagePath === '') {
            return false;
        }

        $encodedBucket = rawurlencode((string) SUPABASE_STORAGE_BUCKET);
        $encodedPath = str_replace('%2F', '/', rawurlencode($storagePath));

        for ($attempt = 1; $attempt <= $attempts; $attempt++) {
            $headResult = supabaseStorageRequest('HEAD', 'object/' . $encodedBucket . '/' . $encodedPath);
            if ($headResult['success']) {
                return true;
            }

            $infoResult = supabaseStorageRequest('GET', 'object/info/' . $encodedBucket . '/' . $encodedPath);
            if ($infoResult['success']) {
                return true;
            }

            if ($attempt < $attempts) {
                usleep($delayMicroseconds);
            }
        }

        error_log('Supabase object existence check failed for ' . $storagePath);
        return false;
    }
}

if (!function_exists('defaultAvatarUrl')) {
    function defaultAvatarUrl(?string $label = null): string
    {
        $label = trim((string) ($label ?? ''));
        if ($label === '') {
            $label = 'User';
        }

        $parts = preg_split('/\s+/', $label) ?: [];
        $initials = '';
        foreach ($parts as $part) {
            $part = trim((string) $part);
            if ($part === '') {
                continue;
            }

            $initial = function_exists('mb_substr') ? mb_substr($part, 0, 1, 'UTF-8') : substr($part, 0, 1);
            $initials .= function_exists('mb_strtoupper') ? mb_strtoupper($initial, 'UTF-8') : strtoupper($initial);

            if (strlen($initials) >= 2) {
                break;
            }
        }

        if ($initials === '') {
            $initials = 'U';
        }

        $safeInitials = htmlspecialchars($initials, ENT_QUOTES, 'UTF-8');
        $svg = <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" role="img" aria-label="{$safeInitials}">
  <defs>
    <linearGradient id="avatarGradient" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#0d6efd"/>
      <stop offset="100%" stop-color="#052c65"/>
    </linearGradient>
  </defs>
  <rect width="120" height="120" rx="60" fill="url(#avatarGradient)"/>
  <text x="50%" y="54%" text-anchor="middle" dominant-baseline="middle" font-family="Arial, Helvetica, sans-serif" font-size="44" font-weight="700" fill="#ffffff">{$safeInitials}</text>
</svg>
SVG;

        return 'data:image/svg+xml;charset=UTF-8,' . rawurlencode($svg);
    }
}

if (!function_exists('storedFileExists')) {
    function storedFileExists(PDO $pdo, ?string $path, ?string $basePath = null): bool
    {
        if ($path === null || $path === '') {
            return false;
        }

        if (strpos($path, 'filedb:') === 0) {
            ensureUploadedFilesTable($pdo);
            $storageKey = substr($path, 7);
            $stmt = $pdo->prepare("SELECT 1 FROM uploaded_files WHERE storage_key = ? LIMIT 1");
            $stmt->execute([$storageKey]);
            return (bool) $stmt->fetchColumn();
        }

        if (strpos($path, 'supabase:') === 0) {
            $storagePath = supabaseStorageNormalizePath(substr($path, 9));
            if ($storagePath === '') {
                return false;
            }

            return supabaseStorageObjectExists($storagePath);
        }

        if (isAbsoluteUrl($path)) {
            return true;
        }

        if ($basePath === null || $basePath === '') {
            return false;
        }

        if (strpos($path, 'uploads/') === 0) {
            $absolutePath = rtrim($basePath, '/\\') . '/public/' . ltrim($path, '/');
            return is_file($absolutePath);
        }

        $absolutePath = rtrim($basePath, '/\\') . '/' . ltrim($path, '/');
        return is_file($absolutePath);
    }
}

if (!function_exists('replaceApplicationDocument')) {
    function replaceApplicationDocument(PDO $pdo, int $documentId, array $file, ?int $expectedUserId = null, ?int $expectedApplicationId = null, ?string $basePath = null): array
    {
        $stmt = $pdo->prepare("
            SELECT id, user_id, application_id, file_name, file_path
            FROM documents
            WHERE id = ?
            LIMIT 1
        ");
        $stmt->execute([$documentId]);
        $document = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$document) {
            return ['success' => false, 'error' => 'Document record not found.'];
        }

        if ($expectedUserId !== null && (int) ($document['user_id'] ?? 0) !== $expectedUserId) {
            return ['success' => false, 'error' => 'You are not allowed to replace this document.'];
        }

        if ($expectedApplicationId !== null && (int) ($document['application_id'] ?? 0) !== $expectedApplicationId) {
            return ['success' => false, 'error' => 'This document does not belong to the selected application.'];
        }

        $ownerId = (int) ($expectedUserId ?? ($document['user_id'] ?? 0));
        $namePrefix = $ownerId > 0 ? 'doc_' . $ownerId . '_' : 'doc_' . $documentId . '_';
        $oldPath = $document['file_path'] ?? '';

        $uploadResult = storeUploadedFile(
            $pdo,
            $file,
            'documents',
            $namePrefix,
            ['application/pdf'],
            appUploadMaxBytes(),
            $basePath
        );

        if (!$uploadResult['success']) {
            return $uploadResult;
        }

        try {
            $updateStmt = $pdo->prepare("
                UPDATE documents
                SET file_name = ?, file_path = ?, uploaded_at = CURRENT_TIMESTAMP
                WHERE id = ?
            ");
            $updateStmt->execute([
                $uploadResult['name'],
                $uploadResult['path'],
                $documentId,
            ]);
        } catch (Throwable $e) {
            deleteStoredFileByPath($pdo, $uploadResult['path'] ?? '', $basePath);
            return ['success' => false, 'error' => 'Failed to update the document record: ' . $e->getMessage()];
        }

        if ($oldPath !== '' && $oldPath !== ($uploadResult['path'] ?? '')) {
            deleteStoredFileByPath($pdo, $oldPath, $basePath);
        }

        return [
            'success' => true,
            'document_id' => $documentId,
            'name' => $uploadResult['name'],
            'path' => $uploadResult['path'],
            'previous_name' => $document['file_name'] ?? '',
            'previous_path' => $oldPath,
        ];
    }
}

if (!function_exists('describeStoredFile')) {
    function describeStoredFile(PDO $pdo, ?string $path, ?string $basePath = null, ?string $fallbackUrl = null): array
    {
        $url = storedFilePathToUrl($path, $fallbackUrl);
        $exists = storedFileExists($pdo, $path, $basePath);

        $reason = '';
        if ($path === null || $path === '') {
            $reason = 'missing_path';
        } elseif (!$exists) {
            if (strpos($path, 'filedb:') === 0) {
                $reason = 'database_file_missing';
            } elseif (strpos($path, 'uploads/') === 0) {
                $reason = 'legacy_upload_missing';
            } else {
                $reason = 'file_missing';
            }
        }

        return [
            'path' => $path ?? '',
            'url' => $url,
            'exists' => $exists,
            'reason' => $reason,
        ];
    }
}

if (!function_exists('deleteStoredFileByPath')) {
    function deleteStoredFileByPath(PDO $pdo, ?string $path, ?string $basePath = null): void
    {
        if ($path === null || $path === '') {
            return;
        }

        if (strpos($path, 'filedb:') === 0) {
            ensureUploadedFilesTable($pdo);
            $storageKey = substr($path, 7);
            $stmt = $pdo->prepare("DELETE FROM uploaded_files WHERE storage_key = ?");
            $stmt->execute([$storageKey]);
            return;
        }

        if (strpos($path, 'supabase:') === 0) {
            $storagePath = supabaseStorageNormalizePath(substr($path, 9));
            if ($storagePath !== '') {
                supabaseStorageRequest(
                    'DELETE',
                    'object/' . rawurlencode((string) SUPABASE_STORAGE_BUCKET),
                    json_encode(['prefixes' => [$storagePath]]),
                    ['Content-Type: application/json']
                );
            }
            return;
        }

        if (strpos($path, 'uploads/') === 0 && $basePath) {
            $absolutePath = rtrim($basePath, '/\\') . '/public/' . ltrim($path, '/');
            if (is_file($absolutePath)) {
                @unlink($absolutePath);
            }
        }
    }
}

if (!function_exists('removeApplicationDocumentFile')) {
    function removeApplicationDocumentFile(PDO $pdo, int $documentId, ?int $expectedUserId = null, ?int $expectedApplicationId = null, ?string $basePath = null): array
    {
        $stmt = $pdo->prepare("
            SELECT id, user_id, application_id, file_name, file_path
            FROM documents
            WHERE id = ?
            LIMIT 1
        ");
        $stmt->execute([$documentId]);
        $document = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$document) {
            return ['success' => false, 'error' => 'Document record not found.'];
        }

        if ($expectedUserId !== null && (int) ($document['user_id'] ?? 0) !== $expectedUserId) {
            return ['success' => false, 'error' => 'You are not allowed to remove this document.'];
        }

        if ($expectedApplicationId !== null && (int) ($document['application_id'] ?? 0) !== $expectedApplicationId) {
            return ['success' => false, 'error' => 'This document does not belong to the selected application.'];
        }

        $oldPath = $document['file_path'] ?? '';

        try {
            $updateStmt = $pdo->prepare("
                UPDATE documents
                SET file_path = NULL, uploaded_at = NULL
                WHERE id = ?
            ");
            $updateStmt->execute([$documentId]);
        } catch (Throwable $e) {
            return ['success' => false, 'error' => 'Failed to clear the document record: ' . $e->getMessage()];
        }

        return [
            'success' => true,
            'document_id' => $documentId,
            'previous_name' => $document['file_name'] ?? '',
            'previous_path' => $oldPath,
        ];
    }
}

if (!function_exists('replaceLegacyMissingDocument')) {
    function replaceLegacyMissingDocument(PDO $pdo, int $documentId, array $file, ?int $expectedUserId = null, ?int $expectedApplicationId = null, ?string $basePath = null): array
    {
        $stmt = $pdo->prepare("
            SELECT id, user_id, application_id, file_name, file_path
            FROM documents
            WHERE id = ?
            LIMIT 1
        ");
        $stmt->execute([$documentId]);
        $document = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$document) {
            return ['success' => false, 'error' => 'Document record not found.'];
        }

        if ($expectedUserId !== null && (int) ($document['user_id'] ?? 0) !== $expectedUserId) {
            return ['success' => false, 'error' => 'You are not allowed to replace this document.'];
        }

        if ($expectedApplicationId !== null && (int) ($document['application_id'] ?? 0) !== $expectedApplicationId) {
            return ['success' => false, 'error' => 'This document does not belong to the selected application.'];
        }

        $fileInfo = describeStoredFile($pdo, $document['file_path'] ?? '', $basePath);
        if (($fileInfo['reason'] ?? '') !== 'legacy_upload_missing') {
            return ['success' => false, 'error' => 'Only missing legacy documents can be replaced from this screen.'];
        }

        return replaceApplicationDocument($pdo, $documentId, $file, $expectedUserId, $expectedApplicationId, $basePath);
    }
}

if (!function_exists('storageSanitizeFilename')) {
    function storageSanitizeFilename(string $originalName): string
    {
        $candidate = trim(str_replace(["\0", "\r", "\n"], '', $originalName));
        $baseName = basename($candidate !== '' ? $candidate : 'file');
        $safeFilename = preg_replace('/[^A-Za-z0-9.\-]/', '_', $baseName);
        $safeFilename = trim((string) $safeFilename, '._');

        return $safeFilename !== '' ? $safeFilename : 'file';
    }
}

if (!function_exists('insertStoredBlobRecord')) {
    function insertStoredBlobRecord(PDO $pdo, string $storageKey, ?string $folder, string $originalName, string $mimeType, int $fileSize, string $blobContents): bool
    {
        if (dbIsPgsql($pdo)) {
            $stmt = $pdo->prepare("
                INSERT INTO uploaded_files (storage_key, folder_name, original_name, mime_type, file_size, content_blob)
                VALUES (?, ?, ?, ?, ?, decode(?, 'hex'))
            ");

            return $stmt->execute([
                $storageKey,
                $folder,
                $originalName,
                $mimeType,
                $fileSize,
                bin2hex($blobContents),
            ]);
        }

        $stmt = $pdo->prepare("
            INSERT INTO uploaded_files (storage_key, folder_name, original_name, mime_type, file_size, content_blob)
            VALUES (?, ?, ?, ?, ?, ?)
        ");
        $stmt->bindValue(1, $storageKey, PDO::PARAM_STR);
        $stmt->bindValue(2, $folder, PDO::PARAM_STR);
        $stmt->bindValue(3, $originalName, PDO::PARAM_STR);
        $stmt->bindValue(4, $mimeType, PDO::PARAM_STR);
        $stmt->bindValue(5, $fileSize, PDO::PARAM_INT);
        $stmt->bindValue(6, $blobContents, PDO::PARAM_LOB);

        return $stmt->execute();
    }
}

if (!function_exists('storeUploadedFileInSupabase')) {
    function storeUploadedFileInSupabase(string $tmpName, string $safeFilename, string $mimeType, string $folder, string $namePrefix): array
    {
        if (!supabaseStorageConfigured()) {
            return ['success' => false, 'error' => 'Supabase Storage is not configured.'];
        }

        $folder = supabaseStorageNormalizePath($folder);
        $prefix = preg_replace('/[^A-Za-z0-9_\-]/', '_', $namePrefix);
        $storageFilename = $prefix . uniqid('', true) . '_' . $safeFilename;
        $storagePath = supabaseStorageNormalizePath(($folder !== '' ? $folder . '/' : '') . $storageFilename);
        $contents = file_get_contents($tmpName);

        if ($contents === false || strlen($contents) === 0) {
            return ['success' => false, 'error' => "Failed to read uploaded file '{$safeFilename}'."];
        }

        $endpoint = 'object/' . rawurlencode((string) SUPABASE_STORAGE_BUCKET) . '/' . str_replace('%2F', '/', rawurlencode($storagePath));
        $result = supabaseStorageRequest(
            'POST',
            $endpoint,
            $contents,
            [
                'Content-Type: ' . $mimeType,
                'cache-control: 3600',
            ]
        );

        if (!$result['success']) {
            error_log('Supabase upload error: ' . json_encode($result));
            return ['success' => false, 'error' => "Failed to store file in Supabase Storage."];
        }

        return [
            'success' => true,
            'name' => $storageFilename,
            'path' => 'supabase:' . $storagePath,
            'url' => storedFilePathToUrl('supabase:' . $storagePath),
        ];
    }
}

if (!function_exists('storeUploadedFile')) {
    function storeUploadedFile(PDO $pdo, array $file, string $folder = '', string $namePrefix = 'file_', ?array $allowedTypes = null, ?int $maxBytes = null, ?string $basePath = null): array
    {
        $allowedTypes = $allowedTypes ?? [];
        $maxBytes = $maxBytes ?? appUploadMaxBytes();

        if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
            return ['success' => false, 'error' => 'Upload failed.'];
        }

        $originalName = trim((string) ($file['name'] ?? ''));
        $mimeType = trim((string) ($file['type'] ?? 'application/octet-stream'));
        $tmpName = $file['tmp_name'] ?? '';
        $fileSize = (int) ($file['size'] ?? 0);

        if ($originalName === '' || $tmpName === '' || !is_uploaded_file($tmpName)) {
            return ['success' => false, 'error' => 'Uploaded file is invalid.'];
        }

        if (!empty($allowedTypes) && !in_array($mimeType, $allowedTypes, true)) {
            return ['success' => false, 'error' => "Invalid file type for '{$originalName}'."];
        }

        if ($fileSize > $maxBytes) {
            return ['success' => false, 'error' => "File '{$originalName}' exceeds the " . appUploadMaxLabel() . ' upload limit.'];
        }

        $folder = trim(str_replace('\\', '/', $folder), '/');
        $safeFilename = storageSanitizeFilename($originalName);
        $prefix = preg_replace('/[^A-Za-z0-9_\-]/', '_', $namePrefix);

        if (appUsesSupabaseUploads()) {
            return storeUploadedFileInSupabase($tmpName, $safeFilename, $mimeType, $folder, $namePrefix);
        }

        if (appUsesDatabaseUploads()) {
            ensureUploadedFilesTable($pdo);
            $storageKey = bin2hex(random_bytes(16));
            $blobContents = file_get_contents($tmpName);

            if ($blobContents === false) {
                return ['success' => false, 'error' => "Failed to read uploaded file '{$originalName}'."];
            }

            if (strlen($blobContents) === 0) {
                return ['success' => false, 'error' => "Uploaded file '{$originalName}' is empty."];
            }

            // Postgres rejects arbitrary binary bytes when they're sent as plain strings.
            // Store bytea values via hex decoding so PDF uploads work reliably in production.
            $result = insertStoredBlobRecord(
                $pdo,
                $storageKey,
                $folder !== '' ? $folder : null,
                $safeFilename,
                $mimeType,
                $fileSize,
                $blobContents
            );
            
            if (!$result) {
                $errorInfo = $pdo->errorInfo();
                error_log("Database insert failed for file '{$originalName}': " . json_encode($errorInfo));
                return ['success' => false, 'error' => "Failed to store file in database."];
            }

            return [
                'success' => true,
                'name' => $safeFilename,
                'path' => 'filedb:' . $storageKey,
                'url' => storedFilePathToUrl('filedb:' . $storageKey),
            ];
        }

        if ($basePath === null || $basePath === '') {
            return ['success' => false, 'error' => 'Local upload path is not configured.'];
        }

        $targetDirectory = rtrim($basePath, '/\\') . '/public/uploads' . ($folder !== '' ? '/' . $folder : '');
        if (!is_dir($targetDirectory) && !@mkdir($targetDirectory, 0777, true)) {
            return ['success' => false, 'error' => 'Failed to create upload directory.'];
        }

        $newFilename = $prefix . uniqid('', true) . '_' . $safeFilename;
        $destination = $targetDirectory . '/' . $newFilename;

        if (!move_uploaded_file($tmpName, $destination)) {
            return ['success' => false, 'error' => "Failed to store uploaded file '{$originalName}'."];
        }

        $relativePath = 'uploads/' . ($folder !== '' ? $folder . '/' : '') . $newFilename;

        return [
            'success' => true,
            'name' => $newFilename,
            'path' => $relativePath,
            'url' => storedFilePathToUrl($relativePath),
        ];
    }
}

if (!function_exists('storeExistingFileFromDisk')) {
    function storeExistingFileFromDisk(PDO $pdo, string $absolutePath, string $originalName, string $folder = '', ?string $basePath = null): array
    {
        if ($absolutePath === '' || !is_file($absolutePath) || !is_readable($absolutePath)) {
            return ['success' => false, 'error' => "File '{$absolutePath}' is not readable."];
        }

        $fileSize = (int) filesize($absolutePath);
        $safeFilename = storageSanitizeFilename($originalName !== '' ? $originalName : $absolutePath);
        $folder = trim(str_replace('\\', '/', $folder), '/');
        $mimeType = function_exists('mime_content_type')
            ? (mime_content_type($absolutePath) ?: 'application/octet-stream')
            : 'application/octet-stream';

        if (appUsesDatabaseUploads()) {
            ensureUploadedFilesTable($pdo);
            $storageKey = bin2hex(random_bytes(16));
            $blobContents = file_get_contents($absolutePath);

            if ($blobContents === false) {
                return ['success' => false, 'error' => "Failed to read file '{$absolutePath}'."];
            }

            if (strlen($blobContents) === 0) {
                return ['success' => false, 'error' => "File '{$absolutePath}' is empty."];
            }

            $result = insertStoredBlobRecord(
                $pdo,
                $storageKey,
                $folder !== '' ? $folder : null,
                $safeFilename,
                $mimeType,
                $fileSize,
                $blobContents
            );
            
            if (!$result) {
                $errorInfo = $pdo->errorInfo();
                error_log("Database insert failed for file '{$absolutePath}': " . json_encode($errorInfo));
                return ['success' => false, 'error' => "Failed to store file in database."];
            }

            return [
                'success' => true,
                'name' => $safeFilename,
                'path' => 'filedb:' . $storageKey,
                'url' => storedFilePathToUrl('filedb:' . $storageKey),
            ];
        }

        if ($basePath === null || $basePath === '') {
            return ['success' => false, 'error' => 'Local upload path is not configured.'];
        }

        $targetDirectory = rtrim($basePath, '/\\') . '/public/uploads' . ($folder !== '' ? '/' . $folder : '');
        if (!is_dir($targetDirectory) && !@mkdir($targetDirectory, 0777, true)) {
            return ['success' => false, 'error' => 'Failed to create upload directory.'];
        }

        $newFilename = uniqid('migrated_', true) . '_' . $safeFilename;
        $destination = $targetDirectory . '/' . $newFilename;

        if (!@copy($absolutePath, $destination)) {
            return ['success' => false, 'error' => "Failed to copy file '{$absolutePath}'."];
        }

        $relativePath = 'uploads/' . ($folder !== '' ? $folder . '/' : '') . $newFilename;

        return [
            'success' => true,
            'name' => $newFilename,
            'path' => $relativePath,
            'url' => storedFilePathToUrl($relativePath),
        ];
    }
}
