<?php

if (!function_exists('isAbsoluteUrl')) {
    function isAbsoluteUrl(?string $value): bool
    {
        if ($value === null) {
            return false;
        }

        return (bool) preg_match('#^(https?:)?//#i', $value);
    }
}

if (!function_exists('appUsesDatabaseUploads')) {
    function appUsesDatabaseUploads(): bool
    {
        return defined('UPLOAD_DRIVER') && UPLOAD_DRIVER === 'database';
    }
}

if (!function_exists('appUsesLocalUploads')) {
    function appUsesLocalUploads(): bool
    {
        return !appUsesDatabaseUploads();
    }
}

if (!function_exists('appUploadMaxBytes')) {
    function appUploadMaxBytes(): int
    {
        return defined('UPLOAD_MAX_BYTES') ? (int) UPLOAD_MAX_BYTES : 4194304;
    }
}

if (!function_exists('appUploadMaxLabel')) {
    function appUploadMaxLabel(): string
    {
        return number_format(appUploadMaxBytes() / 1048576, 0) . 'MB';
    }
}

if (!function_exists('ensureUploadedFilesTable')) {
    function ensureUploadedFilesTable(PDO $pdo): void
    {
        static $initialized = false;

        if ($initialized) {
            return;
        }

        if (dbIsPgsql($pdo)) {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS uploaded_files (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    storage_key VARCHAR(80) NOT NULL UNIQUE,
                    folder_name VARCHAR(120) NULL,
                    original_name VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(120) NOT NULL,
                    file_size INTEGER NOT NULL DEFAULT 0,
                    content_blob BYTEA NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ");
        } else {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS uploaded_files (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    storage_key VARCHAR(80) NOT NULL UNIQUE,
                    folder_name VARCHAR(120) NULL,
                    original_name VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(120) NOT NULL,
                    file_size INT NOT NULL DEFAULT 0,
                    content_blob LONGBLOB NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ");
        }

        $initialized = true;
    }
}

if (!function_exists('storedFilePathToUrl')) {
    function storedFilePathToUrl(?string $path, ?string $fallback = null): string
    {
        if ($path === null || $path === '') {
            return $fallback ?? '';
        }

        if (strpos($path, 'filedb:') === 0) {
            $storageKey = substr($path, 7);
            return rtrim(BASE_URL, '/') . '/api/file.php?key=' . rawurlencode($storageKey);
        }

        if (isAbsoluteUrl($path)) {
            return $path;
        }

        if (strpos($path, 'uploads/') === 0) {
            return rtrim(BASE_URL, '/') . '/public/' . ltrim($path, '/');
        }

        return rtrim(BASE_URL, '/') . '/' . ltrim($path, '/');
    }
}

if (!function_exists('deleteStoredFileByPath')) {
    function deleteStoredFileByPath(PDO $pdo, ?string $path, ?string $basePath = null): void
    {
        if ($path === null || $path === '') {
            return;
        }

        if (strpos($path, 'filedb:') === 0) {
            ensureUploadedFilesTable($pdo);
            $storageKey = substr($path, 7);
            $stmt = $pdo->prepare("DELETE FROM uploaded_files WHERE storage_key = ?");
            $stmt->execute([$storageKey]);
            return;
        }

        if (strpos($path, 'uploads/') === 0 && $basePath) {
            $absolutePath = rtrim($basePath, '/\\') . '/public/' . ltrim($path, '/');
            if (is_file($absolutePath)) {
                @unlink($absolutePath);
            }
        }
    }
}

if (!function_exists('storeUploadedFile')) {
    function storeUploadedFile(PDO $pdo, array $file, string $folder = '', string $namePrefix = 'file_', ?array $allowedTypes = null, ?int $maxBytes = null, ?string $basePath = null): array
    {
        $allowedTypes = $allowedTypes ?? [];
        $maxBytes = $maxBytes ?? appUploadMaxBytes();

        if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
            return ['success' => false, 'error' => 'Upload failed.'];
        }

        $originalName = trim((string) ($file['name'] ?? ''));
        $mimeType = trim((string) ($file['type'] ?? 'application/octet-stream'));
        $tmpName = $file['tmp_name'] ?? '';
        $fileSize = (int) ($file['size'] ?? 0);

        if ($originalName === '' || $tmpName === '' || !is_uploaded_file($tmpName)) {
            return ['success' => false, 'error' => 'Uploaded file is invalid.'];
        }

        if (!empty($allowedTypes) && !in_array($mimeType, $allowedTypes, true)) {
            return ['success' => false, 'error' => "Invalid file type for '{$originalName}'."];
        }

        if ($fileSize > $maxBytes) {
            return ['success' => false, 'error' => "File '{$originalName}' exceeds the " . appUploadMaxLabel() . ' upload limit.'];
        }

        $folder = trim(str_replace('\\', '/', $folder), '/');
        $safeFilename = preg_replace('/[^A-Za-z0-9.\-]/', '_', basename($originalName));
        $prefix = preg_replace('/[^A-Za-z0-9_\-]/', '_', $namePrefix);

        if (appUsesDatabaseUploads()) {
            ensureUploadedFilesTable($pdo);
            $storageKey = bin2hex(random_bytes(16));
            $blobContents = file_get_contents($tmpName);

            if ($blobContents === false) {
                return ['success' => false, 'error' => "Failed to read uploaded file '{$originalName}'."];
            }

            $stmt = $pdo->prepare("
                INSERT INTO uploaded_files (storage_key, folder_name, original_name, mime_type, file_size, content_blob)
                VALUES (?, ?, ?, ?, ?, ?)
            ");
            $stmt->bindValue(1, $storageKey);
            $stmt->bindValue(2, $folder !== '' ? $folder : null);
            $stmt->bindValue(3, $safeFilename);
            $stmt->bindValue(4, $mimeType);
            $stmt->bindValue(5, $fileSize, PDO::PARAM_INT);
            $stmt->bindParam(6, $blobContents, PDO::PARAM_LOB);
            $stmt->execute();

            return [
                'success' => true,
                'name' => $safeFilename,
                'path' => 'filedb:' . $storageKey,
                'url' => storedFilePathToUrl('filedb:' . $storageKey),
            ];
        }

        if ($basePath === null || $basePath === '') {
            return ['success' => false, 'error' => 'Local upload path is not configured.'];
        }

        $targetDirectory = rtrim($basePath, '/\\') . '/public/uploads' . ($folder !== '' ? '/' . $folder : '');
        if (!is_dir($targetDirectory) && !@mkdir($targetDirectory, 0777, true)) {
            return ['success' => false, 'error' => 'Failed to create upload directory.'];
        }

        $newFilename = $prefix . uniqid('', true) . '_' . $safeFilename;
        $destination = $targetDirectory . '/' . $newFilename;

        if (!move_uploaded_file($tmpName, $destination)) {
            return ['success' => false, 'error' => "Failed to store uploaded file '{$originalName}'."];
        }

        $relativePath = 'uploads/' . ($folder !== '' ? $folder . '/' : '') . $newFilename;

        return [
            'success' => true,
            'name' => $newFilename,
            'path' => $relativePath,
            'url' => storedFilePathToUrl($relativePath),
        ];
    }
}

if (!function_exists('storeExistingFileFromDisk')) {
    function storeExistingFileFromDisk(PDO $pdo, string $absolutePath, string $originalName, string $folder = '', ?string $basePath = null): array
    {
        if ($absolutePath === '' || !is_file($absolutePath) || !is_readable($absolutePath)) {
            return ['success' => false, 'error' => "File '{$absolutePath}' is not readable."];
        }

        $fileSize = (int) filesize($absolutePath);
        $safeFilename = preg_replace('/[^A-Za-z0-9.\-]/', '_', basename($originalName !== '' ? $originalName : $absolutePath));
        $folder = trim(str_replace('\\', '/', $folder), '/');
        $mimeType = function_exists('mime_content_type')
            ? (mime_content_type($absolutePath) ?: 'application/octet-stream')
            : 'application/octet-stream';

        if (appUsesDatabaseUploads()) {
            ensureUploadedFilesTable($pdo);
            $storageKey = bin2hex(random_bytes(16));
            $blobContents = file_get_contents($absolutePath);

            if ($blobContents === false) {
                return ['success' => false, 'error' => "Failed to read file '{$absolutePath}'."];
            }

            $stmt = $pdo->prepare("
                INSERT INTO uploaded_files (storage_key, folder_name, original_name, mime_type, file_size, content_blob)
                VALUES (?, ?, ?, ?, ?, ?)
            ");
            $stmt->bindValue(1, $storageKey);
            $stmt->bindValue(2, $folder !== '' ? $folder : null);
            $stmt->bindValue(3, $safeFilename);
            $stmt->bindValue(4, $mimeType);
            $stmt->bindValue(5, $fileSize, PDO::PARAM_INT);
            $stmt->bindParam(6, $blobContents, PDO::PARAM_LOB);
            $stmt->execute();

            return [
                'success' => true,
                'name' => $safeFilename,
                'path' => 'filedb:' . $storageKey,
                'url' => storedFilePathToUrl('filedb:' . $storageKey),
            ];
        }

        if ($basePath === null || $basePath === '') {
            return ['success' => false, 'error' => 'Local upload path is not configured.'];
        }

        $targetDirectory = rtrim($basePath, '/\\') . '/public/uploads' . ($folder !== '' ? '/' . $folder : '');
        if (!is_dir($targetDirectory) && !@mkdir($targetDirectory, 0777, true)) {
            return ['success' => false, 'error' => 'Failed to create upload directory.'];
        }

        $newFilename = uniqid('migrated_', true) . '_' . $safeFilename;
        $destination = $targetDirectory . '/' . $newFilename;

        if (!@copy($absolutePath, $destination)) {
            return ['success' => false, 'error' => "Failed to copy file '{$absolutePath}'."];
        }

        $relativePath = 'uploads/' . ($folder !== '' ? $folder . '/' : '') . $newFilename;

        return [
            'success' => true,
            'name' => $newFilename,
            'path' => $relativePath,
            'url' => storedFilePathToUrl($relativePath),
        ];
    }
}
