CREATE TABLE IF NOT EXISTS application_status_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    old_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    remarks TEXT,
    changed_by VARCHAR(120),
    changed_via VARCHAR(30) NOT NULL DEFAULT 'portal',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_application_status_history_application_created_at
    ON application_status_history (application_id, created_at DESC, id DESC);

ALTER TABLE application_status_history ENABLE ROW LEVEL SECURITY;
