SET search_path TO public;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20),
    birthdate DATE,
    school_id VARCHAR(100) UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'student',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    email_verified SMALLINT NOT NULL DEFAULT 0,
    email_verified_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    student_type VARCHAR(50) DEFAULT 'New Applicant',
    profile_picture_path VARCHAR(255),
    permissions TEXT
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    student_name VARCHAR(255) NOT NULL,
    school_id_number VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(20),
    date_of_birth DATE,
    address TEXT,
    student_type VARCHAR(20) DEFAULT 'new',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scholarships (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    deadline DATE NOT NULL,
    requirements TEXT,
    application_requirements TEXT,
    benefits TEXT,
    available_slots INTEGER DEFAULT 10,
    category VARCHAR(100) DEFAULT 'general',
    accepting_new_applicants SMALLINT NOT NULL DEFAULT 1,
    accepting_renewal_applicants SMALLINT NOT NULL DEFAULT 1,
    amount NUMERIC(10,2) DEFAULT 500.00,
    amount_type VARCHAR(20) NOT NULL DEFAULT 'Peso',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    requires_exam SMALLINT NOT NULL DEFAULT 0,
    passing_grade INTEGER DEFAULT 75,
    passing_score INTEGER DEFAULT 75,
    exam_duration INTEGER DEFAULT 60,
    end_of_term DATE
);

CREATE TABLE IF NOT EXISTS forms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scholarship_id INTEGER NOT NULL REFERENCES scholarships(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS form_fields (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scholarship_id INTEGER REFERENCES scholarships(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    form_id INTEGER REFERENCES forms(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    field_label VARCHAR(255),
    field_name VARCHAR(255),
    field_type VARCHAR(50) NOT NULL DEFAULT 'text',
    field_options TEXT,
    is_required SMALLINT NOT NULL DEFAULT 0,
    field_order INTEGER NOT NULL DEFAULT 0,
    options TEXT
);

CREATE TABLE IF NOT EXISTS applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    scholarship_id INTEGER NOT NULL REFERENCES scholarships(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    scholarship_name VARCHAR(255),
    application_requirements TEXT,
    status VARCHAR(50) DEFAULT 'Pending',
    application_type VARCHAR(20) DEFAULT 'new',
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applicant_type VARCHAR(20) DEFAULT 'New',
    year_program VARCHAR(255),
    program VARCHAR(100),
    year_level VARCHAR(50),
    units_enrolled INTEGER,
    gwa NUMERIC(5,2),
    remarks TEXT,
    student_status VARCHAR(50),
    scholarship_percentage NUMERIC(5,2),
    scholarship_amount NUMERIC(10,2)
);

CREATE TABLE IF NOT EXISTS application_responses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    form_field_id INTEGER NOT NULL REFERENCES form_fields(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    response_value TEXT
);

CREATE TABLE IF NOT EXISTS documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exam_questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scholarship_id INTEGER NOT NULL REFERENCES scholarships(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) NOT NULL,
    options TEXT,
    correct_answer TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exam_submissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    scholarship_id INTEGER NOT NULL REFERENCES scholarships(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    score INTEGER DEFAULT 0,
    total_items INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'in_progress',
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS exam_answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id INTEGER NOT NULL REFERENCES exam_submissions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    question_id INTEGER NOT NULL REFERENCES exam_questions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    student_answer TEXT,
    is_correct SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS application_exams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    score_part_a INTEGER DEFAULT 0,
    answers_part_b TEXT,
    score_part_b INTEGER DEFAULT 0,
    grades_part_b TEXT,
    total_score INTEGER DEFAULT 0,
    is_graded SMALLINT DEFAULT 0,
    admin_remarks TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_path VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS announcement_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id INTEGER NOT NULL REFERENCES announcements(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    file_path VARCHAR(255) NOT NULL,
    file_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    title VARCHAR(255) NOT NULL DEFAULT 'System Notification',
    message TEXT NOT NULL,
    is_read SMALLINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS conversations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    subject VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    message_text TEXT,
    attachment_path VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS support_tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    application_id INTEGER REFERENCES applications(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    subject VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS uploaded_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key VARCHAR(80) NOT NULL UNIQUE,
    folder_name VARCHAR(120),
    original_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    content_blob BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_students_user_id ON students(user_id);
CREATE INDEX IF NOT EXISTS idx_students_school_id_number ON students(school_id_number);
CREATE INDEX IF NOT EXISTS idx_scholarships_deadline ON scholarships(deadline);
CREATE INDEX IF NOT EXISTS idx_scholarships_status ON scholarships(status);
CREATE INDEX IF NOT EXISTS idx_forms_scholarship_id ON forms(scholarship_id);
CREATE INDEX IF NOT EXISTS idx_form_fields_scholarship_id ON form_fields(scholarship_id);
CREATE INDEX IF NOT EXISTS idx_form_fields_form_id ON form_fields(form_id);
CREATE INDEX IF NOT EXISTS idx_applications_student_id ON applications(student_id);
CREATE INDEX IF NOT EXISTS idx_applications_scholarship_id ON applications(scholarship_id);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_applications_applicant_type ON applications(applicant_type);
CREATE INDEX IF NOT EXISTS idx_application_responses_application_id ON application_responses(application_id);
CREATE INDEX IF NOT EXISTS idx_documents_application_id ON documents(application_id);
CREATE INDEX IF NOT EXISTS idx_documents_user_id ON documents(user_id);
CREATE INDEX IF NOT EXISTS idx_exam_questions_scholarship_id ON exam_questions(scholarship_id);
CREATE INDEX IF NOT EXISTS idx_exam_submissions_student_id ON exam_submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_exam_submissions_scholarship_id ON exam_submissions(scholarship_id);
CREATE INDEX IF NOT EXISTS idx_exam_answers_submission_id ON exam_answers(submission_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_student_id ON notifications(student_id);
CREATE INDEX IF NOT EXISTS idx_conversations_student_user_id ON conversations(student_user_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_student_id ON support_tickets(student_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_application_id ON support_tickets(application_id);
CREATE INDEX IF NOT EXISTS idx_support_messages_ticket_id ON support_messages(ticket_id);
